### ISSUE TITLE
Ooops, something went wrong

### ISSUE THREAD

**Issue by Alerinos** [KorzhCom/EasyData#110]
When creating a new item, I get this message:
![image](https://user-images.githubusercontent.com/42449535/150006703-16894fa9-f04e-4d65-993e-7234ac85b772.png)

```
Ooops, something went wrong

Cannot insert duplicate key row in object 'dbo.Games_Culture' with unique index 'IX_Games_Culture_GameId'. The duplicate key value is (55255ee9-f2f6-47fd-9ed4-08d9dab85823). The statement has been terminated.
```
```
[20:31:02 INF] Executed endpoint 'EasyData API'
[20:31:02 INF] Request finished HTTP/1.1 POST http://localhost:5021/crud/games/models/__default/sources/Game/fetch application/json 42 - 200 - application/json;+charset=utf-8 11.9115ms
[20:31:44 INF] Request starting HTTP/1.1 POST http://localhost:5021/crud/games/models/__default/sources/Culture/create application/json 147
[20:31:44 INF] Executing endpoint 'EasyData API'
[20:31:44 INF] Entity Framework Core 6.0.1 initialized 'GamesContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer:6.0.1' with options: SensitiveDataLoggingEnabled
[20:31:44 ERR] Failed executing DbCommand (84ms) [Parameters=[@p0='Long description' (Nullable = false) (Size = 4000), @p1='55255ee9-f2f6-47fd-9ed4-08d9dab85823', @p2='en' (Nullable = false) (Size = 6), @p3='short desc' (Nullable = false) (Size = 160), @p4='Roblox' (Nullable = false) (Size = 70)], CommandType='Text', CommandTimeout='30']
SET NOCOUNT ON;
INSERT INTO [Games_Culture] ([Description], [GameId], [Language], [ShortDescription], [Title])
VALUES (@p0, @p1, @p2, @p3, @p4);
SELECT [Id]
FROM [Games_Culture]
WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();
[20:31:44 ERR] An exception occurred in the database while saving changes for context type 'Lib.Games.GamesContext'.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert duplicate key row in object 'dbo.Games_Culture' with unique index 'IX_Games_Culture_GameId'. The duplicate key value is (55255ee9-f2f6-47fd-9ed4-08d9dab85823).
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__188_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
ClientConnectionId:93f85e3a-2b59-432b-82a5-51d05517b939
Error Number:2601,State:1,Class:14
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert duplicate key row in object 'dbo.Games_Culture' with unique index 'IX_Games_Culture_GameId'. The duplicate key value is (55255ee9-f2f6-47fd-9ed4-08d9dab85823).
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__188_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
ClientConnectionId:93f85e3a-2b59-432b-82a5-51d05517b939
Error Number:2601,State:1,Class:14
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
```
```cs
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapEasyData(options =>
                {
                    options.Endpoint = "/crud/culture";
                    options.UseDbContext<Lib.Culture.CultureContext>();
                });

                endpoints.MapEasyData(options =>
                {
                    options.Endpoint = "/crud/identity";
                    options.UseDbContext<Lib.Identity.IdentityContext>();
                });

                endpoints.MapEasyData(options =>
                {
                    options.Endpoint = "/crud/games";
                    options.UseDbContext<Lib.Games.GamesContext>();
                });

                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");

                endpoints.MapRazorPages();
            });
```

Lib.Games.Models.Game:
```cs
using Core;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Lib.Games.Models;

/*
 * Last update: 18.01.2022
 * Version: 1.0
 * 
 * Główny model gry
 */

public class Game
{
    [Key]
    public Guid Id { get; set; }

    [StringLength(Standard.Types.TitleMaxLength, MinimumLength = Standard.Types.TitleMinLength), Required]
    public string Name { get; set; } = string.Empty;                

    [StringLength(Standard.Types.HashTagMaxLenght, MinimumLength = Standard.Types.HashTagMinLenght), Required]
    public string HashTag { get; set; } = string.Empty;                            
    public StatusType Status { get; set; }                        


    public Culture Culture { get; set; } = new Culture() { Language = "en" };

    public enum StatusType
    {
        Verification,           
        Show,                  
        Hide,                   
        Recommended           
    }

}

```

Lib.Games.Models.Culture:
```cs
using Core;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Lib.Games.Models;

public class Culture
{
    public int Id { get; set; }
    public Game? Game { get; set; }
    public Guid GameId { get; set; }

    [StringLength(Standard.Types.CultureLength), Required]
    public string Language { get; set; } = "en";
                                                                                    
    [StringLength(Standard.Types.TitleMaxLength, MinimumLength = Standard.Types.TitleMinLength), Required]
    public string Title { get; set; } = string.Empty; 

    [StringLength(Standard.Types.DescriptionMaxLength, MinimumLength = Standard.Types.DescriptionMinLength), Required]
    public string ShortDescription { get; set; } = string.Empty; 

    [Column(TypeName = "nvarchar(MAX)"), Required]
    public string Description { get; set; } = string.Empty; 
}
```

**Comment by antifree** [comment]
So the problem is that you trying to add an entity with a duplicated unique index.
It is mean that in your database GameId in Culture could not be duplicated between entities.
This problem is not related to EasyData

**Comment by Alerinos** [comment]
@antifree Actually, I'm sorry. But this is still a slight problem because if it delete:
```cs
public Game? Game { get; set; }
```
At this point, I will not have a relationship with EasyData.
Will try notmapped again
