### ISSUE TITLE
Uncaught DOMException: Failed to execute 'replaceState' on 'History': A history state object with URL 'http://variables/' cannot be created in a document with origin 'http://localhost:5021' and URL 'http://localhost:5021/culture/'.

### ISSUE THREAD

**Issue by Alerinos** [KorzhCom/EasyData#92]
![image](https://user-images.githubusercontent.com/42449535/148813924-2f47b7ca-fcae-4f1f-b0a3-a235ff755f13.png)

```
Uncaught DOMException: Failed to execute 'replaceState' on 'History': A history state object with URL 'http://variables/' cannot be created in a document with origin 'http://localhost:5021' and URL 'http://localhost:5021/culture/'.
    at u (https://cdn.korzh.com/ed/1.4.0/easydata.min.js:2:54269)
    at HTMLLIElement.<anonymous> (https://cdn.korzh.com/ed/1.4.0/easydata.min.js:2:168037)
```

Code:
```
@page "/culture/{url?}"
@model Crud.Pages.EasyDataModel
@{
    ViewData["Title"] = "Entities";
}

<div id="EasyDataContainer"></div>


    <link rel="stylesheet" href="https://cdn.korzh.com/ed/1.4.0/easydata.min.css" />
    <script src="https://cdn.korzh.com/ed/1.4.0/easydata.min.js" type="text/javascript"></script>

    <script>
        window.addEventListener('load', function () {
            new easydata.crud.EasyDataViewDispatcher({
                endpoint: '/ed_culture/crud'
            }).run()
        });
    </script>
```
The problem starts when I change the url in @Page.
My system is based on many databases (One library, one context)
I need to create many subpages, unfortunately with this error it is not possible.

**Comment by Alerinos** [comment]
next problem:
```
easydata.min.js:2 
        
       TypeError: Cannot read properties of undefined (reading 'captionPlural')
    at new t (easydata.min.js:2)
    at t.setActiveView (easydata.min.js:2)
    at easydata.min.js:2
    at A (easydata.min.js:2)
    at k (easydata.min.js:2)
    at MutationObserver.g (easydata.min.js:2)
 ```
 ```
@page "/easydata/culture/{url?}"
```

**Comment by antifree** [comment]
Hello. 

If you change the page URL, please also add the `basePath` option. For example 
for `@page "/culture/{url?}"` will be
```js
  window.addEventListener('load', function () {
            new easydata.crud.EasyDataViewDispatcher({
                endpoint: '/ed_culture/crud',
                basePath: 'culture' 
            }).run()
        });
```

Related issue #4
